module.exports = {
  LOGIN: 'LOGIN',
  ADD_RULE: 'ADD_RULE',
  UPDATE_RULE: 'UPDATE_RULE',
  REMOVE_RULE: 'REMOVE_RULE',
  GET_RULES_LIST: {
    GET_RULES_LIST_REQUEST: 'GET_RULES_LIST_REQUEST',
    GET_RULES_LIST_COMPLETED: 'GET_RULES_LIST_COMPLETED',
    GET_RULES_LIST_FAILED: 'GET_RULES_LIST_FAILED'
  },
  QUERY_STOCK: {
    QUERY_STOCK_REQUEST: 'QUERY_STOCK_REQUEST',
    QUERY_STOCK_COMPLETED: 'QUERY_STOCK_COMPLETED',
    QUERY_STOCK_FAILED: 'QUERY_STOCK_FAILED'
  },
  CREATE_RULE: {
    CREATE_RULE_REQUEST: 'CREATE_RULE_REQUEST',
    CREATE_RULE_COMPLETED: 'CREATE_RULE_COMPLETED',
    CREATE_RULE_FAILED: 'CREATE_RULE_FAILED'
  },
  CLEAR_STOCK: 'CLEAR_STOCK',
  UPDATE_RULE_STATUS: {
    UPDATE_RULE_STATUS_REQUEST: 'UPDATE_RULE_STATUS_REQUEST',
    UPDATE_RULE_STATUS_COMPLETED: 'UPDATE_RULE_STATUS_COMPLETED',
    UPDATE_RULE_STATUS_FAILED: 'UPDATE_RULE_STATUS_FAILED'
  },
  GET_RULE_DETAIL: 'GET_RULE_DETAIL'
};