module.exports = {
  LOGIN: 'LOGIN',
  ADD_RULE: 'ADD_RULE',
  UPDATE_RULE: 'UPDATE_RULE',
  REMOVE_RULE: 'REMOVE_RULE',
  GET_RULES_LIST: {
    GET_RULES_LIST_REQUEST: 'GET_RULES_LIST_REQUEST',
    GET_RULES_LIST_COMPLETED: 'GET_RULES_LIST_COMPLETED',
    GET_RULES_LIST_FAILED: 'GET_RULES_LIST_FAILED'
  },
  GET_RULE_DETAIL: 'GET_RULE_DETAIL'
};